application_root: "E:\\\\Photo\\\\"
application_directories:
   dirs:
   - "temp"
   - "artifact"
   temp:
   - "size_data.txt"
   - "table_data.txt"
   - "instance_data.txt"
   - "removed_files_data.txt"
   - "completed_directories.txt"
   artifact:
   - "blacklist.txt"
   size_data      : "temp\\\\size_data.txt"
   table_data     : "temp\\\\table_data.txt"
   photo_data     : "temp\\\\instance_data.txt"
   removed_files  : "temp\\\\removed_files_data.txt"
   completed_dirs : "temp\\\\completed_directories.txt"

folders:
   good_folder_name:
   - "_Good"
   - "_GOOD"
   - "_good"
   - "Good"
   - "GOOD"
   - "good"
   all_folder_name:
   - "_all"
   - "_ALL"  
   - "all"
   - "All"
   - "ALL"
   crt_folder_name:
   - "_DNG"
   - "DNG"
   - "crt"
   - "CRT"
   - "Crt"
   - "_CRT"
blacklist:
    enabled: true
    location: "artifact\\\\blacklist.txt"

thread:
    instance_multiplier: 1

file_extensions:
   crt:
   - ".CR2"
   - ".dng"
   - ".TIF"
   good:
   - ".jpg"

