application_root: "E:\\Photo\\"
folders:
   good_folder_name:
   - "_Good"
   - "_GOOD"
   - "Good"
   - "GOOD"
   - "good"
   all_folder_name:
   - "_all"
   - "_ALL"  
   - "all"
   - "All"
   - "ALL"
   crt_folder_name:
   - "_DNG"
   - "DNG"
   - "crt"
   - "CRT"
   - "Crt"
   - "CRT"
blacklist:
    enabled: true
    location: "artifact\\blacklist.txt"

file_extensions:
   crt:
   - ".CR2"
   - ".dng"
   - ".TIF"
   good:
   - ".jpg"
  
data:
   index_data: "temp\\photo_directories_data.txt"
   table_data: "  temp\\table_data.txt"
   size_data: "temp\\size_data.txt"
   removed_files_data:   "temp\\removed_files_data.txt"
   completed_directories: "artifact\\completed_directories.txt"  
